Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Glob('jsoncpp/src/lib_json/*.cpp')

if not GetDepend("APP_USING_JSONCPP"):
    src=[]


path = [cwd,str(Dir('#')),cwd+'/jsoncpp/include']


group = DefineGroup('jsoncpp', src, depend = [''], CPPPATH = path,LOCAL_CXXFLAGS='  --gnu --cpp11 --exceptions  ')

Return('group')
